default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] || ENV['POSTGRES_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  timeout: 5000

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
