default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGARESS_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
